---
- name: Tasks to run after rulebook triggered
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Debug message from AAP Controller
      ansible.builtin.debug:
        msg: "Incoming commit: {{ commit_detail }}"
