---
- name: Listen for GitHub commit events and trigger AAP job template
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: https://eda2-aap.wxo4z-opc-opensearch-clus-47e063e6a3ad1f71bf2e58f91c3b4c2e-0000.us-south.containers.appdomain.cloud
        port: 8001
    # - ansible.eda.github:
    #     # token: "your_github_personal_access_token"  # Replace with your GitHub token
    #     repository: "adn1107/ansible-test"       # Replace with your GitHub repository
    #     event_filter: push                          # Listen for push events (commits)
  rules:
    - name: Trigger AAP job template on GitHub commit
      condition: event.payload.ref == "refs/heads/main"  # Trigger only for commits to the main branch
      action:
        run_job_template:
          name: "andy-eda-test"       # Replace with your AAP job template name
          organization: "Default"                   # Replace with your AAP organization
          # controller_url: "https://your-aap-server.com"  # Replace with your AAP server URL
          # controller_token: "your_aap_token"        # Replace with your AAP token

# ---
# - name: Listen for events on a webhook
#   hosts: all
#   sources:
#     - ansible.eda.webhook:
#         host: 0.0.0.0
#         port: 8001
#   rules:
#   #
#   # Process the splunk webhooks
#   #
#     - name: Rules to process Git commit
#       condition: 
#       action:
#         run_job_template:
#           name: eda-template-splunk
#           organization: Default
