---
- name: Listen for GitHub commit events and trigger AAP job template
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Trigger AAP job template on GitHub commit
      condition: event.payload.ref == "refs/heads/main"  # Trigger only for commits to the main branch
      action:
        run_job_template:
          name: "andy-eda-test"       # Replace with your AAP job template name
          organization: "Default"                   # Replace with your AAP organization
          job_args:
            extra_vars:
              message: "{{ event.payload.commits[0].message }}"
